# Specifies the version of the Docker Compose file format we're using.
version: '3.8'

# This section defines all the services (containers) that make up your application.
services:

  # 1. The Backend Service
  backend:
    # Tells Docker to build an image from the Dockerfile located in the './backend' directory.
    build: ./backend
    container_name: secure-share-backend
    ports:
      # Maps port 5001 on your computer to port 5001 inside the container.
      - "5001:5001"
    # This is crucial: it securely loads your .env file from the backend folder into the container.
    env_file:
      - ./backend/.env
    volumes:
      # This line is for development. It syncs your local code with the code inside the container.
      # When you save a file, the container will automatically update.
      - ./backend:/usr/src/app
      # This prevents your local node_modules from overwriting the ones installed inside the container.
      - /usr/src/app/node_modules

  # 2. The Frontend Service
  frontend:
    # Builds the frontend service using the Dockerfile in the './frontend' directory.
    build: ./frontend
    container_name: secure-share-frontend
    ports:
      # Maps port 3000 on your computer to port 80 (Nginx's port) inside the container.
      - "3000:80"
    # This ensures that the frontend container will wait for the backend to be fully started before it starts.
    depends_on:
      - backend

# Defines the virtual network that allows the frontend and backend containers to find and talk to each other.
networks:
  default:
    name: secure-share-network

